### ISSUE TITLE
local

### ISSUE THREAD

**Issue by akmalsabri** [whrrmydragons/Alakazam#7]
how to run locally ?

**Comment by whrrmydragons** [comment]
The documentation is not really up to date ATM.
I replaced flask with FastApi:
https://fastapi.tiangolo.com/
to run you need to install fastapi and uvicorn
and you need to install the requirements from app/requirements.txt
uvicorn main:app --reload.

the easiest way to get to run is with docker and build locally im not sure the image is up to date i will try and check everything today/tommorow to make sure things are up to date.

if you run into any issues please let me know.

Omri

**Comment by akmalsabri** [comment]
I got this error

`Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
.....  `
`File "./main.py", line 43, in <module>
    app.mount("/static", StaticFiles(directory="app/static"), name="static")
  File "/home/ustad/Documents/tf_torch/lib/python3.7/site-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'app/static' does not exist
`
Okay. thank you !. Actually I just starting to learn fastapi from udemy, but not finished yet.
`

**Comment by akmalsabri** [comment]
I think I just moved the main.py outside app folder and run. I dont know if I'm wrong or not

**Comment by whrrmydragons** [comment]
I made a demo site for the project so the I used a static folder to serve it.
The problem is I only checked running through docker.
I pushed a [fix](https://github.com/whrrmydragons/Alakazam/commit/44739822099946839f6f494d3b47268bd8791e7a) to run locally and will fix the docker image and CI soon.

**Comment by akmalsabri** [comment]
Thank you Sir ! and the sample data is from the time series API right?

**Comment by whrrmydragons** [comment]
I took the sample  [data/csv](https://github.com/facebook/prophet/blob/master/examples/example_wp_log_peyton_manning.csv) from [this example](https://facebook.github.io/prophet/docs/quick_start.html#python-api) in the fbprophet documentation.

**Comment by akmalsabri** [comment]
thanks. I learn something from your work.
